// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var Curry      = require("bs-platform/lib/js/curry.js");
var Js_json    = require("bs-platform/lib/js/js_json.js");
var Make       = require("express");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var $$Error = /* module */[];

function method_(req) {
  var s = req.method;
  switch (s) {
    case "CONNECT" : 
        return /* Connect */7;
    case "DELETE" : 
        return /* Delete */3;
    case "GET" : 
        return /* Get */0;
    case "HEAD" : 
        return /* Head */4;
    case "OPTIONS" : 
        return /* Options */5;
    case "POST" : 
        return /* Post */1;
    case "PUT" : 
        return /* Put */2;
    case "TRACE" : 
        return /* Trace */6;
    default:
      return Pervasives.failwith("Express.Request.method_ Unexpected method: " + s);
  }
}

function protocol(req) {
  var s = req.protocol;
  switch (s) {
    case "http" : 
        return /* Http */0;
    case "https" : 
        return /* Https */1;
    default:
      return Pervasives.failwith("Express.Request.protocol, Unexpected protocol: " + s);
  }
}

function accepts(req, types) {
  var ret = req.accepts(types);
  var tagged_t = Js_json.classify(ret);
  if (typeof tagged_t === "number" || tagged_t.tag) {
    return /* None */0;
  } else {
    return /* Some */[tagged_t[0]];
  }
}

function acceptsCharsets(req, types) {
  var ret = req.acceptsCharsets(types);
  var tagged_t = Js_json.classify(ret);
  if (typeof tagged_t === "number" || tagged_t.tag) {
    return /* None */0;
  } else {
    return /* Some */[tagged_t[0]];
  }
}

var Request = /* module */[
  /* method_ */method_,
  /* protocol */protocol,
  /* accepts */accepts,
  /* acceptsCharsets */acceptsCharsets
];

var Response = /* module */[];

function setRespHeaders(res) {
  res.setHeader("Content-Type", "application/json");
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS, PUT, PATCH, DELETE");
  res.setHeader("Access-Control-Allow-Headers", "X-Requested-With,content-type");
  return /* () */0;
}

var middleware = undefined;

function error(e) {
  return e;
}

var Next = /* module */[
  /* middleware */middleware,
  /* route */"route",
  /* error */error
];

var Middleware = /* module */[];

function MakeBindFunctions() {
  return /* module */[];
}

function listen(app, $staropt$star, $staropt$star$1, _) {
  var port = $staropt$star ? $staropt$star[0] : 3000;
  var onListen = $staropt$star$1 ? $staropt$star$1[0] : (function () {
        return /* () */0;
      });
  app.listen(port, Curry.__1(onListen));
  return /* () */0;
}

var App = /* module */[/* listen */listen];

function express() {
  return Make();
}

function defaultOptions() {
  return { };
}

var Static = /* module */[/* defaultOptions */defaultOptions];

exports.$$Error           = $$Error;
exports.Request           = Request;
exports.Response          = Response;
exports.setRespHeaders    = setRespHeaders;
exports.Next              = Next;
exports.Middleware        = Middleware;
exports.MakeBindFunctions = MakeBindFunctions;
exports.App               = App;
exports.express           = express;
exports.Static            = Static;
/* middleware Not a pure module */
